main = "src/index.ts"
compatibility_date = "2025-12-21"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

# Default (no usar en prod)
[vars]
SUPABASE_URL = "https://ambutlpchwroqsgceicw.supabase.co"
FRONTEND_URL = "http://localhost:5173"
ENV = "dev"

[env.dev]
name = "backend-store-check-dev"

[env.dev.vars]
SUPABASE_URL = "https://ambutlpchwroqsgceicw.supabase.co"
FRONTEND_URL = "http://localhost:5173"
ENV = "dev"

[env.prod]
name = "backend-store-check-prod"

[env.prod.vars]
SUPABASE_URL = "https://ambutlpchwroqsgceicw.supabase.co"
FRONTEND_URL = "https://store-check.com"
ENV = "prod"
